package com.aman.dto;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@ToString
@Getter
@Setter
public class DtoOrder {
    private String SUPNAME;
    private String CDES;
    private String NAME;
    private String POSITIONDES;
    private String CURDATE;
    private String ORDNAME;
    private String SUPORDNUM;
    private String PRIVTYPE;
    private String DEALNAME;
    private String PRDNO;
    private String PROJDOCNO;
    private String PROJDES;
    private String STATDES;
    private String OWNERLOGIN;
    private String CODENAME;
    private String CODEDES;
    private String CLOSEDBOOL;
    private String BOOLPCLOSED;
    private String CHANGEFLAG;
    private String TYPECODE;
    private String TYPEDES;
    private String UFLAG;
    private String USERLOGIN;
    private String PROFNUM;
    private String CORDNAME;
    private String DOCQNO;
    private String IMPFNUM;
    private String OTYPE;
    private Double QPRICE;
    private Double PERCENT;
    private Double MAINDISPRICE;
    private Double DISPRICE;
    private Double VAT;
    private Double TOTPRICE;
    private String CODE;
    private String TAXCODE;
    private String WARHSNAME;
    private String LOCNAME;
    private String FORUSERLOGIN;
    private String STCODE;
    private String STDES;
    private String PAYCODE;
    private String PAYDES;
    private String SUPPLNAME;
    private String SUPPLDATE;
    private String PLAN;
    private String PRINTEDBOOL;
    private String LCODE;
    private Double LEXCH;
    private Double ADVPERCENT;
    private Double ADVBAL;
    private String BRANCHNAME;
    private Double VOLUME;
    private String BRANCHDES;
    private String DETAILS;
    private Double TOTQUANT;
    private String BUYERFLAG;
    private Integer CURVERSION;
    private String EXTFILEFLAG;
    private String BONUSFLAG;
    private String CASHFLOWFLAG;
    private String PAYFLAG;
    private String DEPTNAME;
    private String DEPTDES;
    private String INCPARTEXT;
    private String SOXFLAG;
    private String SOXUSERLOGIN;
    private String SOXUDATE;
    private Double SOXAPPPRICE;
    private Double SOXCALPRICE;
    private String AMIR_ORDERARMOR;
    private String AMIR_CUSTNAME;
    private String AMIR_CUSTDES;
    private String AMIR_DESTCODE;
    private String AMIR_CODEDES;
    private String AMIR_ADDRESS;
    private String AMIR_ADDRESS2;
    private String AMIR_STATE;
    private String AMIR_PHONENUM;
    private String AMIR_DISCHARGEWAY;
    private String AMIR_CARTYPE;
    private String AMIR_SUPPLYTIMEFROM;
    private String AMIR_SUPPLYTIMETO;
    private Integer AMIR_CARMELCODE;
    private String AMIR_PDELAYNAME;
    private String AMIR_PDELAYDES;
    private String Y_7349_0_ESHB;
    private String AMIR_DIRECTDEL;
    private String AMIR_FROMCARMELWRHS;
    private String ZAMIR_PORDERDATE;
    private Integer ORD;

}
